version: "3"
services:
  app:
    container_name: app
    image: tfg:latest
    depends_on:
      - db
    ports:
      - "3500:3000"

  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
    mongodata: