version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  db:
    container_name: tfgdatabase
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: